### ISSUE TITLE
run all seven combinations of 1/0 weights on the test dataset

### ISSUE THREAD

**Issue by roblanf** [Tagliacollo/PartitionUCE#12]
then look at the results in R, and think about how you know which are best.

**Comment by Tagliacollo** [comment]
I've tried to run all seven combinations for our test dataset, but I keep getting a ValueError. The error is raised in this part of the code:
--> 142     mean_sses = np.apply_along_axis(np.mean, 1, sses)

and the error says:
     81     if (axis >= nd):
     82         raise ValueError("axis must be less than arr.ndim; axis=%d, rank=%d."
---> 83             % (axis, nd))
     84     ind = [0]*(nd-1)
     85     i = zeros(nd, 'O')

ValueError: axis must be less than arr.ndim; axis=1, rank=1.

I'm struggling with it since yesterday. Any idea how to fix it?
