### ISSUE TITLE
Issue with full_multi and RAxML

### ISSUE THREAD

**Issue by roblanf** [Tagliacollo/PartitionUCE#26]
Hi @Tagliacollo, 

When I run the Crawford full multi analysis in PartitionFinder, I get the following RAxML error: 

```
GTR RAxML was called as follows: /home/rlanfear/github/partitionfinder/programs/raxml_pthreads.linux -f E -s ./analysis/start_tree/filtered_source.phy -m GTRGAMMA -O -n fastTREE -# 1 -p 123456789 -q ./analysis/start_tree/partitions.txt -e 10 -w /home/rlanfear/github/PartitionUCE/processed_data/Crawford_2012/PFfull_multi/analysis/start_tree -T 10 Partition Subset1262 number 1261 has a problem, the number of expected states is 4 the number of states that are present is 3. Please go and fix your data! Empirical base frequency for state number 1 is equal to zero in DNA data partition Subset1262 Since this is probably not what you want to do, RAxML will soon exit.
```

Can you look into this. 

The problem is that there's a subset that doesn't have all the bases in it, so RAxML will not analyse it. This is something we'll need to fix somehow.

The best thing would be to put a catch in our code so that we don't output subsets unless they have all 4 states (or at least, we don't make splits to UCEs unless all splits have all four states). But let me know what you think and what you can come up with!

**Comment by Tagliacollo** [comment]
Hi @roblanf 

Ok. Thanks for the heads up. I'll take a look at our code and let you know my thoughts

**Comment by roblanf** [comment]
Done: https://github.com/Tagliacollo/PartitionUCE/commit/de1de9b1d15f1413b2e2da5d66afd08d2884142d

**Comment by Kamouyiaros** [comment]
Hi I know this is 3 years down the line, but I'm getting the same error. 

`/programs/raxml_pthreads.linux -f E -s ./analysis/start_tree/filtered_source.phy -m GTRGAMMA -O -n fastTREE -# 1 -p 123456789 -q ./analysis/start_tree/partitions.txt -e 10 -w /nobackup/users/r04mk17/PHYLIP/Window/BEAST/analysis/start_tree -T 8 --silent --no-seq-check Partition Subset5 number 4 has a problem, the number of expected states is 4 the number of states that are present is 2. Please go and fix your data! Empirical base frequency for state number 1 is equal to zero in DNA data partition Subset5 Since this is probably not what you want to do, RAxML will soon exit. Empirical base frequency for state number 2 is equal to zero in DNA data partition Subset5 Since this is probably not what you want to do, RAxML will soon exit.`

I'm not sure what I can do to my data (I can't reduce the number of blocks any further without cutting out gene boundaries). If it's something glaringly obvious that I've missed I apologise, but any advice would greatly help!

**Comment by roblanf** [comment]
@Kamouyiaros can you post the commandline you are using?
